---
- name: Set clusters activity list
  hosts: localhost
  gather_facts: false
  vars:
    dynamic_var_name: "{{ cluster_name }}_activities"
  vars_files:
    - "record/clusters/{{ cluster_name }}.yml"
  tasks:

    - name: Print before setting artifacts
      debug:
        msg: "{{ vars[dynamic_var_name] }}"


    - name: Set artifacts
      ansible.builtin.set_stats:
        data:
          activities: "{{ vars[dynamic_var_name] }}"
          
