---
- name: Set clusters activity list
  hosts: localhost
  gather_facts: false
  vars:
    dynamic_var_name: "{{ cluster_name }}_activities"

  tasks:
 
    - name: Include cluster-specific vars file
      include_vars:
        file: "record/clusters/{{ cluster_name }}.yml"
      ignore_errors: yes

    - name: Print before setting artifacts
      debug:
        msg: "{{ vars[dynamic_var_name] | default('No activities found') }}"

    - name: Set artifacts
      ansible.builtin.set_stats:
        data:
         "{{ dynamic_var_name }}": "{{ vars[dynamic_var_name] | default([]) }}" 
          dogs: "IM a dog hello hello"
          cluster_name: "hi"
