---
- name: Set clusters activity list
  hosts: localhost
  gather_facts: false
  vars:
    dynamic_var_name: "{{ cluster_name }}_activities"

  tasks:
 
    - name: Include cluster-specific vars file
      include_vars:
        file: "record/clusters/{{ cluster_name }}.yml"
      ignore_errors: yes

    - name: Print before setting artifacts
      debug:
        msg: "{{ completed_activities | default('No activities found') }}"

    - name: Set artifacts
      ansible.builtin.set_stats:
        data:
          "completed_activities": "{{ completed_activities | default([]) }}" 
