---
- name: hello
  hosts: localhost
  gather_facts: false
  vars:
    dest_dir: "record/clusters/{{ cluster_name }}.yml"
    combined_name: "{{ cluster_name }}_activities"
  tasks:

  # Clone git repo
  # set the write files as set_stat
    - name: hi shalom1
      debug:
        msg: "HALLL"
        
    - name: set fact
      ansible.builtin.set_stats:
        data:
          activity: "blop blop"
          dog: "IM a dog hello hello"
        
    - name: 
      debug:
        msg: "{{ cluster_x_activities }}"

    - name: 
      debug:
        msg: "{{ combined_name }}"

        
    # - name: 
    #   debug:
    #     msg: "{{ hostvars[cluster_name][combined_name] }}"
