---
- name: hello
  hosts: localhost
  gather_facts: false
  vars:
    dest_dir: "record/clusters/{{ cluster_name }}.yml"
  tasks:

  # Clone git repo
  # set the write files as set_stat
    - name: hi shalom1
      debug:
        msg: "HALLL"
        
    - name: set fact
      ansible.builtin.set_stats:
        data:
          activity: "blop blop"
          dog: "IM a dog hello hello"
    - name: 
      set_fact:
        combined_name: "{{ cluster_name }}_activities"

        
    - name: 
      debug:
        msg: "{{ combined_name }}"
