---
- name: Set clusters activity list
  hosts: localhost
  gather_facts: false
  vars:
    dynamic_var_name: "{{ cluster_name }}_activities"
  vars_files:
    - "record/clusters/{{ cluster_name }}.yml"
  tasks:

    # - name: setfacts something
    #   set_fact:
    #     dynamic_var_name: "{{ cluster_name }}_activities"

    - name: Access the dynamic variable using vars lookup
      debug:
        msg: "{{ vars[dynamic_var_name] }}"


    - name: set fact for bla bla bla 
      ansible.builtin.set_stats:
        data:
          activity: "{{ vars[dynamic_var_name] }}"
          
