---
- name: hello
  hosts: localhost
  gather_facts: false
  vars:
    repo_url: "https://github.com/sfine01/blablabla.git"
    dest_dir: "/tmp/"
  tasks:

  # Clone git repo
  # set the write files as set_stat
    - name: hi shalom1
      debug:
        msg: "HALLL"
        
    - name: set fact
      ansible.builtin.set_stats:
        data:
          cluster: "{{ shopping }}"
          activity: "blop blop"
          dog: "IM a dog hello hello"

    - name: set fact
      shell:
        cmd: pwd
        
    - name: set fact
      shell:
        cmd: ls
