---
- name: hello
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: hi shalom
      debug:
        msg: "HALLL"
        
    - name: set fact
      ansible.builtin.set_stats:
        data:
          dog: "IM a dog hello hello"

    - name: hi shalom
      debug:
        var: shopping_list‎
