---
- name: Check and update activity files
  hosts: localhost
  vars:
    cluster_name: "example_cluster2"  # Default value, should be overridden
    activity_names: ["example_activity1", "example_activity2"]  # Default values, should be overridden
    time: "2024-07-22T12:00:00Z"  # Default value, should be overridden
    activities_path: "records/activities/"
  
  tasks:
  
    - name: Check if activity file exists
      stat:
        path: "{{ activities_path }}{{ item }}.yml"
      register: activity_file_status
      loop: "{{ activity_names }}"

    # - name: Process non-existing activity files
    #   when: activity_file_status.results | selectattr('stat.exists', 'equalto', False) | list | length > 0
    #   block:
    #     - name: Create new activity file
    #       copy:
    #         dest: "{{ activities_path }}{{ item.item }}.yml"
    #         content: |
    #           {{ item.item }}:
    #           - name: {{ cluster_name }}
    #             time: {{ time }}
    #       loop: "{{ activity_file_status.results | selectattr('stat.exists', 'equalto', False) | list }}"
    #       loop_control:
    #         label: "{{ item.item }}"

########################################################
    - name: debug1
      debug:
        msg: "{{ item.stat.path  }}"
      loop: "{{ activity_file_status.results | selectattr('stat.exists', 'equalto', True) | list }}"
      loop_control:
        label: "{{ item.stat.path }}"
      

    - name: test add things to a file
      blockinfile:
        path: "{{ item.stat.path }}" 
        marker: ""
        block: |
          - name: {{ cluster_name }}
            time: {{ time }}
        loop: "{{ activity_file_status.results | selectattr('stat.exists', 'equalto', True) | list}}"
        loop_control:
          label: "{{ item.stat.path }}"


    # - name: Process existing activity files
    #   when: activity_file_status.results | selectattr('stat.exists', 'equalto', True) | list | length > 0
    #   block:
    #     - name: Read content of existing activity file
    #       slurp:
    #         path: "{{ item.item.path }}"
    #       register: existing_content
    #       loop: "{{ activity_file_status.results | selectattr('stat.exists', 'equalto', True) | list }}"
    #       loop_control:
    #         label: "{{ item.item.path }}"

    #     - name: Append to existing activity file
    #       copy:
    #         dest: "{{ item.item.path }}"
    #         content: |
    #           {{ existing_content.results[itemloop.index0].content | b64decode | from_yaml | to_nice_yaml }}
    #           - name: {{ cluster_name }}
    #             time: {{ time }}
    #       loop: "{{ activity_file_status.results | selectattr('stat.exists', 'equalto', True) | list }}"
    #       loop_control:
    #         label: "{{ item.item.path }}"

  
    - name: Check if activity file exists
      shell: ls records/activities/

    - name: print AAAAAAAAAAAAAA
      shell: cat records/activities/example_activity1.yml
      
    - name: print BBBBBBBBBBBBBBBB
      shell: cat records/activities/example_activity2.yml
