---
- name: Check and update activity files
  hosts: localhost
  vars:
    cluster_name: "example_cluster2"  # Default value, should be overridden
    activity_names: ["example_activity12", "example_activity22"]  # Default values, should be overridden
    time: "2024-07-23"  # Default value, should be overridden
    
    activities_path: "records/activities/"
    cluster_file_path: "records/clusters/{{ cluster_name }}.yml"
  
  tasks:
  
    - name: Check if activity file exists
      stat:
        path: "{{ cluster_file_path }}"
      register: cluster_file_status

    - name: Create new activity file
      copy:
        dest: "{{ cluster_file_path }}"
        content: |
          {{ cluster_name}}:
      when: cluster_file_status.stat.exists == false
    
    - name:
      shell: cat "records/clusters/{{ cluster_name }}.yml"
    # - name: Append new activities to Type1 file
    #   blockinfile:
    #     path: "{{ cluster_file_path }}"
    #     marker: ""
    #     create: no
    #     block: |
    #       {{ '- name: ' ~ item | indent(6, True) }}
    #       {{ time | indent(6) }}
    #   loop: "{{ activity_names }}"
    
    - name: Append activities to file
      shell: "echo - name: {{ item }}\n  time: {{ time }} >> {{ cluster_file_path }}"
      loop: "{{ activity_names }}"
      
    - name:
      shell: cat "records/clusters/{{ cluster_name }}.yml"

################################# 

    # - name: Check if activity file exists
    #   stat:
    #     path: "{{ activities_path }}{{ item }}.yml"
    #   register: activity_file_status
    #   loop: "{{ activity_names }}"

    # - name: Process non-existing activity files
    #   when: activity_file_status.results | selectattr('stat.exists', 'equalto', False) | list | length > 0
    #   block:
    #     - name: Create new activity file
    #       copy:
    #         dest: "{{ activities_path }}{{ item.item }}.yml"
    #         content: |
    #           {{ item.item }}:
    #           - name: {{ cluster_name }}
    #             time: {{ time }}
    #       loop: "{{ activity_file_status.results | selectattr('stat.exists', 'equalto', False) | list }}"
    #       loop_control:
    #         label: "{{ item.item }}"

    # - name: test add things to a file
    #   blockinfile:
    #     path: "{{ item.stat.path }}" 
    #     marker: ""
    #     block: |
    #       - name: {{ cluster_name }}
    #         time: {{ time }}
    #   loop: "{{ activity_file_status.results | selectattr('stat.exists', 'equalto', True) | list }}"
    #   loop_control:
    #     label: "{{ item.stat.path }}"
