---
- name: hello
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:

  # Clone git repo
  # set the write files as set_stat
  # deal wit the following options 
   # 1. files are not present 
   # 2. files are presnt
   # 3. somefile are present :)

