---
- name: Check and update activity files
  hosts: localhost
  vars:
    cluster_name: "example_cluster"  # Default value, should be overridden
    activity_names: ["example_activity1", "example_activity2"]  # Default values, should be overridden
    time: "2024-07-22T12:00:00Z"  # Default value, should be overridden
    activities_path: "/records/activities/"
  
  tasks:
  
    - name: Check if activity files exists
      stat:
        path: "{{ activities_path }}{{ item }}.yaml"
      register: activity_file_status
      loop: "{{ activity_names }}"
    
    - name: Update or create activity file
      block:
        - name: Read existing activity file
          slurp:
            path: "{{ activities_path }}{{ item }}.yaml"
          register: existing_content
          when: activity_file_status.results[itemloop.index0].stat.exists

        - name: Append to existing activity file
          copy:
            dest: "{{ activities_path }}{{ item }}.yaml"
            content: |
              {{ existing_content.content | b64decode | from_yaml | to_nice_yaml }}
              - name: {{ cluster_name }}
                time: {{ time }}
          when: activity_file_status.results[itemloop.index0].stat.exists

        - name: Create new activity file
          copy:
            dest: "{{ activities_path }}{{ item }}.yaml"
            content: |
              {{ item }}:
              - name: {{ cluster_name }}
                time: {{ time }}
          when: not activity_file_status.results[itemloop.index0].stat.exists
      loop: "{{ activity_names }}"
