---
- name: cluster sync operation
  hosts: localhost
  match_multiple_rules: true
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5050
        data_alerts_path: alerts
        data_host_path: labels.instance
        data_path_separator: .
        skip_original_data: true
        
  rules:
  
    - name: Get clusters activity list
      condition: event.alert.labels.alertname == "ClusterUp"
      action:
        run_job_template:
          name: mynameisshay
          organization: Default
          post_events: true
          
###############################################################

    - name: Do things 1
      condition: event.dog == "IM a dog hello hello"
      actions:
        - run_job_template:
            name: copy_all_the_files
            organization: Default
          
    - name: Do things 2
      condition: event.dogs == "IM a dog hello hello"
      actions:
        - debug:
            msg: "HELLOOO"
        - set_fact:
            fact:
              activities: "Im a var"

    - name: Do things 3
      condition: event.dogs == "IM a dog hello helloo"
      actions:
        - debug:
            msg: "doing something 33"
        - set_fact:
            fact:
              activities: "{{ activities + ['NahNahNah'] }}"

    - name: print things list
      condition: event.dogs == "IM a dog hello hello"
      action:
        debug:
          msg: "{{ activities }}"

###############################################################

    # - name: Update record files
    #   condition: event.alert.labels.alertname == "ClusterUp" ##### If the activities list is empty dont do anything
    #   action:
    #     run_job_template:
    #       name: mynameisshay
    #       organization: Default
    #       post_events: true
    #       job_args: # pass here the set facts I have defined
