---
- name: Capture alertmanager alerts
  hosts: localhost
  match_multiple_rules: true
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5050
        data_alerts_path: alerts
        data_host_path: labels.instance
        data_path_separator: .
        skip_original_data: true



  rules:

    - name: print something
      condition: event.alert.labels.alertname == "ClusterUp"
      action:
        debug:
          msg: "helooooooooooooooooo"


    - name: activates a playbook
      condition: event.alert.labels.alertname == "ClusterUp"
      action:
        run_job_template:
          name: mynameisshay
          organization: Default

    - name: prints something2
      condition: event.alert.labels.alertname == "ClusterUp"
      action:
        debug:
          msg: "helooooooooooooooooo"
