---
- name: Capture alertmanager alerts
  hosts: localhost
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5050
        data_alerts_path: alerts
        data_host_path: labels.instance
        data_path_separator: .
        skip_original_data: true



  rules:

    - name: asd2222
      condition: event.alert.labels.alertname == "ClusterUp"
      action:
        run_job_template:
          name: mynameisshay
          Organization: Default

    - name: asdasd
      condition: event.alert.labels.alertname == "ClusterUp" 
      action:
        debug:
          msg: "kaki"
