---
- name: Listen for events on a webhook
  hosts: all
  match_multiple_rules: true
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
  
    - name: Get clusters activity list
      condition: event.payload.message == "hi"
      action:
        run_job_template:
          name: mynameisshay
          organization: Default
          post_events: true
          
##################################################################

    - name: Do things 1               # the condition should check that the cluster file doesnt contains the activity name!!!!
      condition:                          
        all:
          - event.cluster_x_activities is selectattr('name', '==', 'run_to_the_tree')
          - event.payload.message is defined
      actions:
        - run_job_template:
            name: copy_all_the_files 
            organization: Default
            job_args:
              limit: "{{ events.m_1.payload.message }}" ##in the message should be the cluster name
          
    # - name: Do things 1                   ### This is working with a simple list without the time in it, seems like the time brakes it
    #   condition:                          
    #     all:
    #       - event.cluster_x_activities contains events.m_1.payload.message
    #   actions:
    #     - run_job_template:
    #         name: copy_all_the_files 
    #         organization: Default
    #         job_args:
    #           limit: "{{ events.m_1.payload.message }}"
    #     - post_event:
    #         event:
    #           activity_name: "hallo" 

              
# #########################################################################
#     - name: Do things 3
#       condition:
#         any:
#           - event.activity_name is defined
#       actions:
#         - run_job_template:
#             name: hiiiiiiiiiiiiiiiiiiiiiiiiiiii
#             organization: Default



