---
- name: Listen for events on a webhook
  hosts: all
  match_multiple_rules: true
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
  
    - name: Get clusters activity list
      condition: event.payload.message is defined
      action:
        run_job_template:
          name: get_activities
          organization: Default
          post_events: true
          job_args:
            limit: "{{ event.payload.message }}"
            
##################################################################

    - name: do_things_1               # the condition should check that the cluster file doesnt contains the activity name!!!!
      condition:                          
        all:
          - event.completed_activities is not selectattr('name', '==', 'do_things_1')
          - event.payload.message is defined
      actions:
        - run_job_template:
            name: do_things_1 
            organization: Default
            job_args:
              limit: "{{ events.m_1.payload.message }}" 
        - post_event:
            event:
              activity_name: "do_things_1" 

    - name: do_things_2
      condition:                          
        all:
          - event.completed_activities is not selectattr('name', '==', 'do_things_2')
          - event.payload.message is defined
      actions:
        - run_job_template:
            name: do_things_2 
            organization: Default
            job_args:
              limit: "{{ events.m_1.payload.message }}" 
        - post_event:
            event:
              activity_name: "do_things_2"

              
    # - name: Run XYXYXYXY              
    #   condition:                          
    #     all:
    #       - event.cluster_x_activities is not selectattr('name', '==', 'XYXYXYXY')
    #       - event.payload.message is defined
    #   actions:
    #     - run_job_template:
    #         name: XYXYXYXY 
    #         organization: Default
    #         job_args:
    #           limit: "{{ events.m_1.payload.message }}" 
    #     - post_event:
    #         event:
    #           activity_name: "XYXYXYXY" 

              
# #########################################################################
    - name: Add activity name to the list               ############# This will run each time evet.activity_name will be defined
      condition:
        any:
          - event.activity_name is defined
      actions:
        - run_job_template:
            name: patch_activity
            organization: Default
            job_args:
              shay: fine



