---
- name: Listen for events on a webhook
  hosts: all
  match_multiple_rules: true
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
  
    - name: Get clusters activity list
      condition: event.payload.message == "hi"
      action:
        run_job_template:
          name: mynameisshay
          organization: Default
          post_events: true
          
##################################################################
          
    - name: Do things 1
      condition: event.cats == 'IM a Cat'
      actions:
        - run_job_template:
            name: copy_all_the_files
            organization: Default
        - post_event:
            event:
              activity_name: "hallo" 

    - name: Do things 2
      condition: event.dogs == 'IM a dog hello hello'
      actions:
        - run_job_template:
            name: copy_all_the_files
            organization: Default
        - post_event:
            event:
               activity_name: "plz plz work"

#########################################################################
    - name: Do things 3
      condition:
        any:
          - event.activity_name is defined
      actions:
        - run_job_template:
            name: hiiiiiiiiiiiiiiiiiiiiiiiiiiii
            organization: Default



