---
- name: Listen for events on a webhook
  hosts: all
  match_multiple_rules: true
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
  
    - name: Get clusters activity list
      condition: event.payload.message == "hi"
      action:
        run_job_template:
          name: mynameisshay
          organization: Default
          post_events: true
          
##################################################################

    - name: Do things 1               # the condition should check that the cluster file doesnt contains the activity name!!!!
      condition:                          
        all:
          - event.cluster_x_activities is selectattr('name', '==', 'run_to_the_tree')
          - event.payload.message is defined
      actions:
        - run_job_template:
            name: copy_all_the_files 
            organization: Default
            job_args:
              limit: "{{ events.m_1.payload.message }}" ##in the message should be the cluster name
        - post_event:
            event:
              activity_name: "run_to_the_tree" 
              

    # - name: Run XYXYXYXY              
    #   condition:                          
    #     all:
    #       - event.cluster_x_activities is selectattr('name', '==', 'XYXYXYXY')
    #       - event.payload.message is defined
    #   actions:
    #     - run_job_template:
    #         name: XYXYXYXY 
    #         organization: Default
    #         job_args:
    #           limit: "{{ events.m_1.payload.message }}" ##in the message should be the cluster name
    #     - post_event:
    #         event:
    #           activity_name: "XYXYXYXY" 

              
# #########################################################################
    - name: This will pach the name activitys to git but just one each time                  ############# This will run each time evet.activity_name will be defined
      condition:
        any:
          - event.activity_name is defined
      actions:
        - run_job_template:
            name: hiiiiiiiiiiiiiiiiiiiiiiiiiiii
            organization: Default



