---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
  
    - name: Get clusters activity list
      condition: event.alert.labels.alertname == "ClusterUp"
      action:
        run_job_template:
          name: mynameisshay
          organization: Default
          post_events: true

    - name: Set fact
      condition: event.meta is defined
      action:
        debug:
