---
- name: Listen for events on a webhook
  hosts: all
  match_multiple_rules: true
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
  
    - name: Get clusters activity list
      condition: event.payload.message == "hi"
      action:
        run_job_template:
          name: mynameisshay
          organization: Default
          post_events: true
          
#################################################
          
    - name: Do things 1
      condition: event.cats == 'IM a Cat'
      actions:
        - run_job_template:
            name: copy_all_the_files
            organization: Default
        - set_fact:
            fact:
              blaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: "hallo"



    - name: Set fact
      condition: event.meta is defined
      action:
        debug:
